# Generated by Django 4.2.9 on 2026-01-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NumberProperty",
            fields=[
                (
                    "number",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("is_prime", models.BooleanField(default=False)),
                ("is_composite", models.BooleanField(default=False)),
                ("is_fibonacci", models.BooleanField(default=False)),
                ("is_triangular", models.BooleanField(default=False)),
                ("is_square", models.BooleanField(default=False)),
                ("is_cube", models.BooleanField(default=False)),
                ("is_tetrahedral", models.BooleanField(default=False)),
                ("is_square_pyramidal", models.BooleanField(default=False)),
                ("is_star", models.BooleanField(default=False)),
                ("is_pentagonal", models.BooleanField(default=False)),
                ("prime_position", models.IntegerField(blank=True, null=True)),
                ("composite_position", models.IntegerField(blank=True, null=True)),
                ("fibonacci_position", models.IntegerField(blank=True, null=True)),
                ("triangular_position", models.IntegerField(blank=True, null=True)),
                ("square_position", models.IntegerField(blank=True, null=True)),
                ("cube_position", models.IntegerField(blank=True, null=True)),
                ("tetrahedral_position", models.IntegerField(blank=True, null=True)),
                (
                    "square_pyramidal_position",
                    models.IntegerField(blank=True, null=True),
                ),
                ("star_position", models.IntegerField(blank=True, null=True)),
                ("pentagonal_position", models.IntegerField(blank=True, null=True)),
                ("prime_nth_value", models.IntegerField(blank=True, null=True)),
                ("composite_nth_value", models.IntegerField(blank=True, null=True)),
                ("fibonacci_nth_value", models.IntegerField(blank=True, null=True)),
                ("triangular_nth_value", models.IntegerField(blank=True, null=True)),
                ("square_nth_value", models.IntegerField(blank=True, null=True)),
                ("cube_nth_value", models.IntegerField(blank=True, null=True)),
                ("tetrahedral_nth_value", models.IntegerField(blank=True, null=True)),
                (
                    "square_pyramidal_nth_value",
                    models.IntegerField(blank=True, null=True),
                ),
                ("star_nth_value", models.IntegerField(blank=True, null=True)),
                ("pentagonal_nth_value", models.IntegerField(blank=True, null=True)),
                ("divisors_count", models.IntegerField(blank=True, null=True)),
                ("divisors_sum", models.IntegerField(blank=True, null=True)),
                ("divisors_list", models.JSONField(blank=True, null=True)),
                ("conversion_binary", models.CharField(blank=True, max_length=50)),
                ("conversion_octal", models.CharField(blank=True, max_length=50)),
                ("conversion_duodecimal", models.CharField(blank=True, max_length=50)),
                ("conversion_hexadecimal", models.CharField(blank=True, max_length=50)),
                ("roman_numeral", models.CharField(blank=True, max_length=50)),
                ("natural_logarithm", models.FloatField(blank=True, null=True)),
                (
                    "condensed_number",
                    models.IntegerField(
                        help_text="The core numerological value used in prediction formula"
                    ),
                ),
                ("properties_json", models.JSONField(blank=True, default=dict)),
                ("source_url", models.URLField(blank=True)),
                ("scraped_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Number Property",
                "verbose_name_plural": "Number Properties",
                "db_table": "number_properties",
                "ordering": ["number"],
            },
        ),
    ]
