# Generated by Django 4.2.9 on 2026-01-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("number_properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="numberproperty",
            name="pd_value",
            field=models.IntegerField(
                blank=True,
                help_text="Pd value: number of sides for geometric shapes, position for numeric sequences",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="numberproperty",
            name="primary_sequence",
            field=models.CharField(
                blank=True,
                help_text="Primary highlighted sequence from Gematrinator",
                max_length=100,
            ),
        ),
    ]
