# Generated by Django 4.2.9 on 2026-01-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DateNumerology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                (
                    "num1",
                    models.IntegerField(help_text="Month + Day + Century + Decade"),
                ),
                (
                    "num2",
                    models.IntegerField(help_text="Month + Day + Year Digits Sum"),
                ),
                ("num3", models.IntegerField(help_text="All Digits Sum")),
                ("num4", models.IntegerField(help_text="Month + Day + Decade")),
                ("num5", models.IntegerField(help_text="Digits Without Century")),
                ("num6", models.IntegerField(help_text="Day of Year")),
                ("num7", models.IntegerField(help_text="Days Remaining in Year")),
                ("num8", models.IntegerField(help_text="Month + Day")),
                (
                    "num9",
                    models.IntegerField(
                        help_text="Month Digits + Day Digits + Century + Decade"
                    ),
                ),
                (
                    "num10",
                    models.IntegerField(help_text="Month + Day + Decade Digits Sum"),
                ),
                (
                    "num11",
                    models.IntegerField(help_text="Month Digits + Day Digits + Decade"),
                ),
                (
                    "num12",
                    models.IntegerField(
                        help_text="Product of All Digits with Full Year"
                    ),
                ),
                (
                    "num13",
                    models.IntegerField(
                        help_text="Product of Digits with Last 2 Year Digits"
                    ),
                ),
                ("numerologies_json", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Date Numerology",
                "verbose_name_plural": "Date Numerologies",
                "db_table": "date_numerologies",
                "ordering": ["-date"],
            },
        ),
    ]
